import express from "express";
import multer from "multer";
import adminController from "../controllers/adminController";
import validate from "../middlewares/express_validator";
import auth from "../middlewares/auth";
const routes = express();
const storage = multer.memoryStorage();
const upload = multer({ storage: storage });
// routes.post("/auth", adminController.auth);
routes.post("/login", validate.login, adminController.login);
routes.post("/addAdmin", auth.auth, auth.isRole, validate.addAdmin, adminController.addAdmin);
routes.get("/getAdminNotification", auth.auth, auth.isRole, adminController.getAdminNotification);
routes.post("/acceptCourse", auth.auth, auth.isRole, validate.acceptCourse, adminController.acceptCourse);
routes.post("/rejectCourse", auth.auth, auth.isRole, validate.rejectCourse, adminController.rejectCourse);
routes.get("/viewTransactionOfUser", auth.auth, auth.isRole, validate.viewTransactionOfUser, adminController.viewTransactionOfUser);
routes.get("/viewAllTransaction", auth.auth, auth.isRole, adminController.viewAllTransaction);
routes.get("/viewAllUserData", auth.auth, auth.isRole, adminController.viewAllUserData);
routes.get("/viewAllStudent", auth.auth, auth.isRole, adminController.viewAllStudent);
routes.get("/viewAllTeacher", auth.auth, auth.isRole, adminController.viewAllTeacher);
routes.patch("/editStudentData", auth.auth, auth.isRole, validate.editStudentData, adminController.editStudentData);
routes.patch("/editTeacherData", auth.auth, auth.isRole, validate.editTeacherData, adminController.editTeacherData);
routes.delete("/deleteStudent", auth.auth, auth.isRole, validate.deleteStudent, adminController.deleteStudent);
routes.delete("/deleteCourseAdmin", auth.auth, auth.isRole, validate.deleteCourseAdmin, adminController.deleteCourseAdmin);
routes.post("/viewCart", adminController.viewCart);
routes.post("/getInstructor", auth.auth, auth.isRole, adminController.getInstructor);
routes.post("/getCourseById", auth.auth, adminController.getCourseById);
export default routes;