import express from "express";
import multer from "multer";
import courseController from "../controllers/courseController";
import validate from "../middlewares/express_validator";
import auth from "../middlewares/auth";
import { uploadFile } from "../util/multer_config";
const routes = express();
const storage = multer.memoryStorage();
const upload = multer({ storage: storage });
routes.get("/getEnrolledCourses", auth.auth, auth.isStudent, courseController.getEnrolledCourses);
routes.get("/getNotEnrolledCourses", auth.auth, auth.isStudent, courseController.getNotEnrolledCourses);
routes.post("/getAllSection", courseController.getAllSection);
routes.post("/getAllSectionData", courseController.getAllSectionData);
routes.post("/getAllSubSection", courseController.getAllSubSection);
routes.get("/getCourseByInstructor", auth.auth, auth.isStudent, courseController.getCourseByInstructor);
routes.post("/markAsCompleted", auth.auth, auth.isStudent, courseController.markAsCompleted);
routes.post("/progressCounter", auth.auth, courseController.progressCounter);
routes.get("/getStudentEnrolled", auth.auth, auth.isStudent, courseController.getStudentEnrolled);
routes.post("/findSubsection", courseController.findSubsection);
routes.post("/getCourseById", courseController.getCourseById);
routes.get("/getCoursesByInstructor", auth.auth, auth.isInstructor, courseController.getCoursesByInstructor);
routes.patch("/editCourse", auth.auth, auth.isInstructor, uploadFile.single('image'), courseController.editCourse);
routes.patch("/editSection", auth.auth, auth.isInstructor, courseController.editSection);
routes.post("/deleteCourse", auth.auth, auth.isInstructor, courseController.deleteCourse);
routes.post("/deleteSection", auth.auth, auth.isInstructor, courseController.deleteSection);
routes.get("/getAllCourse", courseController.getAllCourse);
export default routes;